Astronaut:
  type: object
  config:
    fields:
      id:
        type: 'String!'
      pseudo:
        type: 'String!'
      grade:
        type: 'Grade'
      planet:
        type: 'Planet'
#        resolve: "@=service('planet.resolver').resolveInAstronaut(value, args, context, info)"
        resolve: '@=resolver("App\\Resolver\\PlanetResolver::resolveInAstronaut", [value, args, context, info])'