Query:
  type: object
  config:
    fields:
      Astronaut:
        type: 'Astronaut'
        args:
          id:
            description: 'Resolves Astronaut using its id.'
            type: 'String!'
        resolve: "@=resolver('Astronaut', [args['id']])"
      Astronauts:
        type: '[Astronaut]'
        args:
          limit:
            description: 'Resolves Astronaut using its limit.'
            type: 'Int'
          pseudo:
            description: 'Resolves Astronaut using its limit.'
            type: 'String'
        resolve: "@=resolver('Astronauts', [args['limit'], args['pseudo']] )"
      Planet:
        type: 'Planet'
        args:
          id:
            description: 'Resolves Planet using its id.'
            type: 'String!'
        resolve: "@=resolver('Planet', [args['id']])"